# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: febe56d1fdd75613c6b6681eb2fc23ef19bcc9e1dbcd8cac2d314312f8f2d301d460958373cf83d45e210bb358452cc9d7ada95d870a437497684557153f67fd

test:
  secret_key_base: 9340e5c032de9d40b03198ecae0cc669c6bf9ad92c3344caa24e240e19b24584c13f2be1671a24aeed78972a90704b5be3349ca9300394b52579ef61cc6dc864

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
